apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
	
	path('', views.Listar_Noticias, name = 'listar'),

	path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),
	
	path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
	
	path('eliminar_comentario/<int:comentario_id>/', views.eliminar_comentario, name='eliminar_comentario'),
    
	path('modificar_comentario/<int:comentario_id>/', views.Modificar_Comentario, name='modificar_comentario'),
    
	path('crear_noticia/', views.crear_noticia, name='crear_noticia'),
    
	path('eliminar_noticia/<int:pk>/', views.eliminar_noticia, name='eliminar_noticia'),
    
	path('editar_noticia/<int:pk>/', views.editar_noticia, name='editar_noticia'),
    
	path('eliminar_comentario/<int:comentario_id>/', views.eliminar_comentario2, name='eliminar_comentario'),
    
	path('modificar_comentario/<int:comentario_id>/', views.Modificar_Comentario2, name='modificar_comentario'),
    
	path('crear_categoria/', views.crear_categoria, name='crear_categoria'),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    path('Nosotros/', views.Nosotros, name = 'nosotros'),
    path('Contacto/', views.Contacto, name = 'contacto'),

    #LOGIN
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

class Categoria(models.Model):
	nombre = models.CharField(max_length = 60, unique=True)

	def __str__(self):
		return self.nombre

class Noticia(models.Model):

	titulo = models.CharField(max_length = 150)
	cuerpo = models.TextField()
	imagen = models.ImageField(upload_to = 'noticias')
	categoria_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.titulo

class Comentario(models.Model):
	usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
	texto = models.TextField(max_length = 1500)
	noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.noticia}->{self.texto}"
	
	def puede_eliminar(self, usuario):
		return usuario.is_staff or usuario == self.usuario
	
	def puede_modificar(self, usuario):
		return usuario.is_staff or usuario == self.usuario

	
	

apps/noticias/forms.py
# En el archivo noticias/forms.py
from django import forms
from .models import Noticia, Categoria

class CrearNoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ['titulo', 'cuerpo', 'imagen', 'categoria_noticia']

class CrearCategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']

apps/noticias/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Noticia, Categoria, Comentario
from django.urls import reverse_lazy
from django.http import HttpResponseBadRequest
from django.contrib.auth.decorators import user_passes_test
from .forms import CrearNoticiaForm, CrearCategoriaForm
from django.contrib import messages

def es_personal(user):
    return user.is_staff

def Listar_Noticias(request):
    contexto = {}

    id_categoria = request.GET.get('id', None)
    orden = request.GET.get('orden', None)

    noticias = Noticia.objects.order_by('-fecha')

    if id_categoria:
        noticias = noticias.filter(categoria_noticia=id_categoria)

    if orden == 'asc':
        noticias = noticias.order_by('fecha')
    elif orden == 'desc':
        noticias = noticias.order_by('-fecha')
    elif orden == 'alpha_asc':
        noticias = noticias.order_by('titulo')
    elif orden == 'alpha_desc':
        noticias = noticias.order_by('-titulo')

    contexto['noticias'] = noticias

    cat = Categoria.objects.all().order_by('nombre')
    contexto['categorias'] = cat

    return render(request, 'noticias/listar.html', contexto)



def Detalle_Noticias(request, pk):
	contexto = {}

	n = Noticia.objects.get(pk = pk) #RETORNA SOLO UN OBEJTO
	contexto['noticia'] = n

	c = Comentario.objects.filter(noticia = n)
	contexto['comentarios'] = c

	return render(request, 'noticias/detalle.html',contexto)

@login_required
def Comentar_Noticia(request):

	com = request.POST.get('comentario',None)
	usu = request.user
	noti = request.POST.get('id_noticia', None)# OBTENGO LA PK
	noticia = Noticia.objects.get(pk = noti) #BUSCO LA NOTICIA CON ESA PK
	coment = Comentario.objects.create(usuario = usu, noticia = noticia, texto = com)

	return redirect(reverse_lazy('noticias:detalle', kwargs={'pk': noti}))

@login_required
def eliminar_comentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)

    if request.user == comentario.usuario:
        comentario.delete()
    return redirect('noticias:detalle', pk=comentario.noticia.pk)

@login_required
def Modificar_Comentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)

    
    if not comentario.puede_modificar(request.user):
        return HttpResponseBadRequest("No tienes permisos para modificar este comentario.")

    if request.method == 'POST':
        nuevo_texto = request.POST.get('nuevo_texto', None)

        
        if nuevo_texto:
            comentario.texto = nuevo_texto
            comentario.save()

            
            return redirect('noticias:detalle', pk=comentario.noticia.pk)

    
    return render(request, 'noticias/modificar_comentario.html', {'comentario': comentario})


def crear_noticia(request):
    if request.method == 'POST':
        formulario = CrearNoticiaForm(request.POST, request.FILES)
        if formulario.is_valid():
            nueva_noticia = formulario.save()
            return redirect('noticias:detalle', pk=nueva_noticia.pk) 
    else:
        formulario = CrearNoticiaForm()

    return render(request, 'noticias/crear_noticia.html', {'formulario': formulario})

def crear_categoria(request):
    if request.method == 'POST':
        formulario = CrearCategoriaForm(request.POST)
        if formulario.is_valid():
            nuevo_categoria = formulario.save()
            return redirect('noticias:crear_noticia')
    else:
        formulario = CrearCategoriaForm()

    return render(request, 'noticias/crear_categoria.html', {'formulario': formulario})

@user_passes_test(es_personal)
def eliminar_noticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    noticia.delete()
    messages.success(request, 'La noticia ha sido eliminada exitosamente.')
    return redirect('noticias:listar')

@user_passes_test(es_personal)
def eliminar_comentario2(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    comentario.delete()
    return redirect('noticias:detalle', pk=comentario.noticia.pk)

@user_passes_test(es_personal)
def Modificar_Comentario2(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)

    # Verificar si el usuario es staff o el autor del comentario
    if request.user.is_staff or request.user == comentario.usuario:
        if request.method == 'POST':
            nuevo_texto = request.POST.get('nuevo_texto', None)

            if nuevo_texto:
                comentario.texto = nuevo_texto
                comentario.save()

                return redirect('noticias:detalle', pk=comentario.noticia.pk)

        return render(request, 'noticias/modificar_comentario.html', {'comentario': comentario})
    else:
        return HttpResponseBadRequest("No tienes permisos para modificar este comentario.")

@user_passes_test(es_personal)
def editar_noticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)

    if request.method == 'POST':
        formulario = CrearNoticiaForm(request.POST, request.FILES, instance=noticia)
        if formulario.is_valid():
            formulario.save()
            return redirect('noticias:detalle', pk=noticia.pk)
    else:
        formulario = CrearNoticiaForm(instance=noticia)

    return render(request, 'noticias/editar_noticia.html', {'formulario': formulario, 'noticia': noticia})


#{'nombre':'name', 'apellido':'last name', 'edad':23}
#EN EL TEMPLATE SE RECIBE UNA VARIABLE SEPARADA POR CADA CLAVE VALOR
# nombre
# apellido
# edad

'''
ORM

CLASE.objects.get(pk = ____)
CLASE.objects.filter(campos = ____)
CLASE.objects.all() ---> SELECT * FROM CLASE

'''

templates/noticias/crear_categoria.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Crea Categorias - SA{% endblock titulo %}

{% block contenido %}
<div class="contenedor-total">
    <div class="conteiner-crear-categoria">
        <h1>Crear una nueva Categoria</h1>
        <div>
            <form method="post" enctype="multipart/form-data" class="formulario-crear-categoria">
                {% csrf_token %}
                {{ formulario.as_p }}
                <button type="submit">Crear</button>
            </form>
        </div>
        <div class="crear-categoria-cancelar">
            <a href="{% url 'noticias:crear_noticia' %}">Cancelar</a>
        </div>
    </div>
</div>
<br><br><br><br><br>
{% endblock contenido %}

templates/noticias/crear_noticia.html
<!-- En noticias/templates/noticias/crear_noticia.html -->
{% extends 'base.html' %}

{% block titulo %}Crea Noticias - SA{% endblock titulo %}

{% block contenido %}
  <div class="contenedor-crear-noti">
    <h1>Crear Noticia</h1>
    <form method="post" enctype="multipart/form-data" class="formulario-centrado">
      {% csrf_token %}
      {{ formulario.as_p }}
      <button type="submit">Guardar Noticia</button>
    </form>
    <div class="crear-categoria-container">
      <p class="linea-categoria"></p>
      <a href="{% url 'noticias:crear_categoria' %}" class="crear-categoria">Crear Nueva Categoría</a>
      <p class="linea-categoria"></p>
    </div>
  </div>
{% endblock %}

templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}{{noticia.titulo}}{% endblock titulo %}


{% block contenido %}

<!-- <div class="contenedor-aside">
	<aside>
		<div class="aside1">
			<h4>Recomendados</h4>
			<img src="{% static 'img/IA-1.jpg' %}" alt="">
			<h2>Titulo titulo titulo titulo titulo</h2>
			<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt aliquam repellendus natus sit beatae inventore dicta autem adipisci praesentium explicabo.</p>
			<a href="#"><button>Leer más</button></a>
		</div>
		<div class="aside2">
			<img src="{% static 'img/IA-1.jpg' %}" alt="">
			<h2>Titulo titulo titulo titulo titulo</h2>
			<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt aliquam repellendus natus sit beatae inventore dicta autem adipisci praesentium explicabo.</p>
			<a href="#"><button>Leer más</button></a>
		</div>
		<div class="aside3">
			<img src="{% static 'img/IA-1.jpg' %}" alt="">
			<h2>Titulo titulo titulo titulo titulo</h2>
			<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt aliquam repellendus natus sit beatae inventore dicta autem adipisci praesentium explicabo.</p>
			<a href="#"><button>Leer más</button></a>
		</div>
		<br><br><br><br><br><br><br><br><br><br><br><br>
	</aside>
</div> -->

<body class="detalle-body">
	<div class="content">
		<article>
			<div class="fecha-titulo">
				<p>Fecha: {{noticia.fecha}}</p>
				<h1>{{noticia.titulo}}</h1>
			</div>
			<div class="imagen">
				<img src="{{noticia.imagen.url}}">
			</div>
			<div class="cuerpo">
				<p>{{noticia.cuerpo|linebreaks}}</p><br><br>
				<p>Categoria: {{noticia.categoria_noticia}}</p>
			</div>
			
			<form class="comentario" method="POST" action="{% url 'noticias:comentar' %}">{% csrf_token %}
				<h3>Haz tu comentario</h3>
				<textarea name="comentario" maxlength="1500" onfocus="if(this.value=='Comentario...')this.value='';" onblur="if(this.value=='')this.value='Comentario...';">Comentario...</textarea>
				<input type="text" name="id_noticia" value="{{noticia.pk}}" hidden=""> 
				<input type="submit" value="Guardar">
			</form>
			<div class="seccion-comentarios">
				<h3>COMENTARIOS</h3>
				<p class="linea"></p>
				{% for com in comentarios %}
					<div class="comentario-item">
						<strong class="fecha">Fecha:{{ com.fecha_modificacion|default:com.fecha }}</strong><br><br>
						<strong class="usuario">{{ com.usuario }}</strong><br>
					</div>
					<div class="comentario-normal">
						<p>{{ com.texto }}</p>
					</div>
					<div class="boton">
						{% if user == com.usuario %}
							<a class="eliminar" href="{% url 'noticias:eliminar_comentario' com.id %}" title="Eliminar">
								<i class="fas fa-trash-alt"></i>
							</a>
							<a class="modificar" href="{% url 'noticias:modificar_comentario' com.id %}" title="Editar">
								<i class="fas fa-edit"></i>
							</a>
						{% endif %}
						{% if user.is_staff and user != com.usuario %}
							<a class="eliminar" href="{% url 'noticias:eliminar_comentario' comentario_id=com.pk %}" title="Eliminar">
								<i class="fas fa-trash-alt"></i>
							</a>
							<a class="modificar" href="{% url 'noticias:modificar_comentario' comentario_id=com.pk %}" title="Editar">
								<i class="fas fa-edit"></i>
							</a>
						{% endif %}
						<p></p>
					</div>
					
				{% endfor %}

				<a class="volver-lista" href="{% url 'noticias:listar' %}">Volver</a>
			</div>
		</article>
	</div>
	<div>
		<aside class="aside">
			
		</aside>		
	</div>
</body>
	
{% endblock contenido %}

templates/noticias/editar_noticia.html
{% extends 'base.html' %}

{% block titulo %}Editar Noticia - SA{% endblock titulo %}

{% block contenido %}
    <div class="editar-noticia">
        <h1>Editar Noticia</h1>
        <form method="POST" enctype="multipart/form-data" class="editar-noticia-form">
            {% csrf_token %}
            {{ formulario.as_p }}
            <button type="submit">Guardar Cambios</button>
        </form>
        <a class="editar-noti-cancelar" href="{% url 'noticias:detalle' pk=noticia.pk %}">Cancelar</a>
    </div>
{% endblock %}

templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Noticias sobre Inteligencia Artificial - SA{% endblock titulo %}

{% block contenido %}

<!-- <div class="contenedor-aside">
	<aside>
		<div class="aside1">
			<h4>Recomendados</h4>
			<img src="{% static 'img/IA-1.jpg' %}" alt="">
			<h2>Titulo titulo titulo titulo titulo</h2>
			<a href="#"><button>Leer más</button></a>
		</div>
		<div class="aside2">
			<img src="{% static 'img/IA-1.jpg' %}" alt="">
			<h2>Titulo titulo titulo titulo titulo</h2>
			<a href="#"><button>Leer más</button></a>
		</div>
		<div class="aside3">
			<img src="{% static 'img/IA-1.jpg' %}" alt="">
			<h2>Titulo titulo titulo titulo titulo</h2>
			<a href="#"><button>Leer más</button></a>
		</div>
	</aside>
</div> -->

<body>
	<!-- Lista desplegable -->
	<div class="dropdown">
		<select id="filtrar" name="filtrar" onchange="window.location.href=this.value" class="select">
			<option class="option" value="{% url 'noticias:listar' %}">Filtrar y Ordenar</option>
	
			<optgroup label="Categorías">
				<option class="option" value="{% url 'noticias:listar' %}">TODAS</option>
				{% for cat in categorias %}
					<option class="option" value="?id={{cat.pk}}&orden={{orden}}">{{cat.nombre}}</option>
				{% endfor %}
			</optgroup>
	
			<optgroup label="Por Antigüedad">
				<option class="option" value="?orden=asc&id={{id_categoria}}">Más antiguas primero</option>
				<option class="option" value="?orden=desc&id={{id_categoria}}">Más recientes primero</option>
			</optgroup>
	
			<optgroup label="Por Orden Alfabético">
				<option class="option" value="?orden=alpha_asc&id={{id_categoria}}">A-Z</option>
				<option class="option" value="?orden=alpha_desc&id={{id_categoria}}">Z-A</option>
			</optgroup>
		</select>
	</div>	

	<!-- Listado de noticias -->
	<div class="container">
		{% for noti in noticias %}
		<div class="card">
			<figure>
				<img src="{{noti.imagen.url}}" alt="">
			</figure>
			<div class="contenido">
				<h3>{{noti.titulo}}</h3>
				<p>FECHA: {{noti.fecha}}</p>
				<p>CATEGORIA: {{noti.categoria_noticia}}</p>
				<div class="botones">
					<a href="{% url 'noticias:detalle' noti.pk %}">Leer más</a>
					{% if user.is_staff %}
						<a href="{% url 'noticias:eliminar_noticia' pk=noti.pk %}" title="Eliminar">
							<i class="fas fa-trash-alt"></i>
						</a>
						<a href="{% url 'noticias:editar_noticia' pk=noti.pk %}" title="Editar">
							<i class="fas fa-edit"></i>
						</a>
					{% endif %}
				</div>
			</div>
		</div>
		{% if forloop.counter|divisibleby:3 and not forloop.last %}
            </div><div class="container">
        {% endif %}
		{% endfor %}
	</div>
</body>

{% endblock contenido %}

templates/noticias/modificar_comentario.html
<!-- modificar_comentario.html -->
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Modificar Comentario - SA{% endblock titulo %}

{% block contenido %}
<div class="seccion-modificar-container">
    <div class="seccion-modificar">
        <h2>Modificar Comentario</h2>
        <form method="POST" action="{% url 'noticias:modificar_comentario' comentario.id %}">
            {% csrf_token %}
            <textarea name="nuevo_texto" maxlength="1500">{{ comentario.texto }}</textarea>
            <input type="submit" value="Guardar">
        </form>
        <a class="volver-detalle" href="{% url 'noticias:detalle' pk=comentario.noticia.pk %}">Cancelar</a>
    </div>
</div>
<br><br>
{% endblock %}

templates/noticias/paginador.html
{%if is_paginated %}
    <div style="border: 1px solid blue; float: left right; display: block; margin: 20px; padding: 5px;">
        <span>Paginador:</span>

        {% if page_obj.has_previous %}
        <span> ir a <a href="?page={{page_obj.previous_page_number}}">Atras</a></span>
        {% endif %}

        <span> | pagina: {{page_obj.number}} |</span>

        {% if page_obj.has_next %}
        <span> ir a : <a href="?page={{page_obj.next_page_number}}">Siguiente</a></span>
        {% endif %}

        <span> | {{page_obj.paginator.num_pages}} paginas</span>
    </div>
{% endif %}