apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),

    path('editar-perfil/', views.editar_perfil, name='editar_perfil'),

    path('mi-cuenta/', views.mi_cuenta, name='mi_cuenta'),

    path('cambio-contrasena/', views.cambio_contrasena, name='cambio_contrasena'),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    path('Nosotros/', views.Nosotros, name = 'nosotros'),
    path('Contacto/', views.Contacto, name = 'contacto'),

    #LOGIN
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

class PerfilUsuario(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='perfilusuario')

apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)
    avatar = forms.ImageField(label='Avatar', required=False)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
            'avatar'
        ]

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'username', 'email', 'avatar']

apps/usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RegistroForm, UsuarioForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import PerfilUsuario
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
# Create your views here.

class Registro(CreateView):
    form_class = RegistroForm
    success_url = reverse_lazy('login')
    template_name = 'usuarios/registro.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        # Crea un perfil de usuario asociado al nuevo usuario
        PerfilUsuario.objects.create(user=self.object)
        return response

def mi_cuenta(request):
    return render(request, 'usuarios/mi-cuenta.html')

@login_required
def editar_perfil(request):
    if request.method == 'POST':
        usuario_form = UsuarioForm(request.POST, instance=request.user)
        if usuario_form.is_valid():
            usuario = usuario_form.save(commit=False)
            usuario.save()
            messages.success(request, 'Tu perfil ha sido actualizado con éxito.')
            return redirect('home') 
        else:
            messages.error(request, 'Por favor, corrige los errores a continuación.')
    else:
        usuario_form = UsuarioForm(instance=request.user)

    return render(request, 'usuarios/editar_perfil.html', {'usuario_form': usuario_form})

def cambio_contrasena(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) 
            messages.success(request, 'Contraseña actualizada con éxito.')
            return redirect('usuarios:mi_cuenta')
        else:
            messages.error(request, 'Corrige los errores a continuación.')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'usuarios/cambio_contrasena.html', {'form': form})

templates/usuarios/cambio_contrasena.html
{% extends 'base.html' %}

{% block titulo %}Cambio Contraseña - SA{% endblock titulo %}

{% block contenido %}
  <div class="cambio-contrasena">
    <h2>Cambio de Contraseña</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Cambiar Contraseña</button>
    </form>
    <a href="{% url 'usuarios:mi_cuenta' %}">Cancelar</a>
  </div>
{% endblock contenido %}

templates/usuarios/editar_perfil.html
{% extends 'base.html' %}

{% block titulo %}Editar Perfil - SA{% endblock titulo %}

{% block contenido %}
<div class="editar-perfil">
  <h2>Editar Perfil</h2>
  <form method="post" enctype="multipart/form-data" class="perfil-form">
    {% csrf_token %}
    {{ usuario_form.as_p }}
    <button type="submit">Guardar cambios</button>
  </form>
  <a href="{% url 'usuarios:mi_cuenta' %}" class="cancelar">Cancelar</a>
</div>
{% endblock contenido %}

templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Iniciar Sesión - SA{% endblock titulo %}

{% block contenido %}
<div class="body-login">
	<div class="login-box">
		<img class="avatar" src="{% static 'img/login/logo-login.png' %}" alt="">
		<h1>Ingresa a tu cuenta</h1>
		<form method="POST">{% csrf_token %}
			{{form.errors}}
			<label for="nombre">Usuario</label>
			<input type="text" name="username">
			<label for="password">Contraseña</label>
			<input type="password" name="password">

			<input type="submit" name="" value="INGRESAR">

			<a href="">¿Olvidaste la contraseña?</a><br>
			<a href="{% url 'usuarios:registro' %}">Registrarse</a>
		</form>
	</div>
</div>
	
{% endblock %}

templates/usuarios/mi-cuenta.html
{% extends 'base.html' %}

{% block titulo %}Mi cuenta - SA{% endblock titulo %}

{% block contenido %}
<div class="user-profile">
  <h3>Perfil</h3>
  <h1>{{ request.user.username }}</h1>
  {% if request.user.profile.avatar %}
      <img src="{{ request.user.profile.avatar.url }}" alt="Avatar del usuario">
  {% endif %}
  

  <!-- Información del usuario -->
  <div class="user-info">
    <div class="datos">
      <p>- Usuario: {{ request.user.username }}</p>
      <p>- Nombre: {{ request.user.first_name }}</p>
      <p>- Apellido: {{ request.user.last_name }}</p>
      <p>- Correo: {{ request.user.email }}</p>
      <p>- Fecha de Registro: {{ request.user.date_joined }}</p>
    </div>
    <div class="botones">
      <p class="linea-perfil"></p>
      <a href="{% url 'usuarios:editar_perfil' %}">Editar Perfil</a>
      <p class="linea-perfil"></p>
      <a href="{% url 'usuarios:cambio_contrasena' %}">Cambiar Contraseña</a>
      <p class="linea-perfil"></p>
    </div>
  </div>
  
</div>
  
{% endblock contenido %}

templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Registrarse en el sitio - SA{% endblock titulo %}

{% block contenido %}

<div class="body-registro">
  <form method="Post" class="registro-form">{% csrf_token %}
    <img class="avatar" src="{% static 'img/login/logo-login.png' %}" alt="">
    <h3>Registrarse</h3>
    <div class="form-group">
      <label for="{{ form.first_name.id }}">Nombre</label>
      {{ form.first_name }}
      <label for="{{ form.last_name.id }}">Apellido</label>
      {{ form.last_name }}
      <label for="{{ form.username.id }}">Nombre de Usuario</label>
      {{ form.username }}
      <label for="{{ form.email.id }}">Email</label>
      {{ form.email }}
      <label for="{{ form.password1.id }}">Contraseña</label>
      {{ form.password1 }}
      <label for="{{ form.password2.id }}">Confirmar Contraseña</label>
      {{ form.password2 }}

      <input type="submit" name="" value="CONFIRMAR">

      <a href="{% url 'login' %}">Ya tengo una cuenta</a>
    </div>
  </form>
</div>

{% endblock contenido %}