apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
	
	path('', views.Listar_Noticias, name = 'listar'),

	path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),
	
	path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
	
	path('eliminar_comentario/<int:comentario_id>/', views.eliminar_comentario, name='eliminar_comentario'),
    
	path('modificar_comentario/<int:comentario_id>/', views.Modificar_Comentario, name='modificar_comentario'),
    
	path('crear_noticia/', views.crear_noticia, name='crear_noticia'),
    
	path('eliminar_noticia/<int:pk>/', views.eliminar_noticia, name='eliminar_noticia'),
    
	path('editar_noticia/<int:pk>/', views.editar_noticia, name='editar_noticia'),
    
	path('eliminar_comentario/<int:comentario_id>/', views.eliminar_comentario2, name='eliminar_comentario'),
    
	path('modificar_comentario/<int:comentario_id>/', views.Modificar_Comentario2, name='modificar_comentario'),
    
	path('crear_categoria/', views.crear_categoria, name='crear_categoria'),
    
]

apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),

    path('editar-perfil/', views.editar_perfil, name='editar_perfil'),

    path('mi-cuenta/', views.mi_cuenta, name='mi_cuenta'),

    path('cambio-contrasena/', views.cambio_contrasena, name='cambio_contrasena'),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    path('Nosotros/', views.Nosotros, name = 'nosotros'),
    path('Contacto/', views.Contacto, name = 'contacto'),

    #LOGIN
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block titulo %}Inteligencia Artificial en Acción: Transformando el Mañana{% endblock titulo %}</title>
	<link rel="shortcut icon" href="{% static 'img/logo-sa.png' %}">
	<script src="https://kit.fontawesome.com/eb496ab1a0.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="fontawesome/fontawesome-free-6.5.1-web/css/all.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" 
	integrity="sha512-jBkA7+TvsRNbWy0yND5Pbz2i5Zl2WM+aD3Pz1HFX1ZFvqPifSUC/5AizZyNFsQECobk39rYl5XzQKrKFMy6IXg==" crossorigin="anonymous" />
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<!-- Navbar -->
<body>
	<header>
		<nav>
			<img href="{% url 'home' %}" src="{% static 'img/logo-sa.png' %}" width="60px" height="55px">
			<div class="menu">
				<ul class="list">
					<li><a href="{% url 'home' %}"><i class="fas fa-home" style="margin-right: 5px;"></i> Inicio</a></li>
					<li><a href="{% url 'noticias:listar' %}"><i class="fas fa-newspaper" style="margin-right: 5px;"></i> Categorias</a></li>
					<li><a href="{% url 'nosotros' %}"><i class="fas fa-user" style="margin-right: 5px;"></i> Acerca de</a></li>
					<li><a href="{% url 'contacto' %}"><i class="fas fa-envelope" style="margin-right: 5px;"></i> Contacto</a></li>
					{% if user.is_staff %}
                    	<li><a href="{% url 'noticias:crear_noticia' %}"><i class="fas fa-edit" style="margin-right: 5px;"></i> Crear Noticia</a></li>
                	{% endif %}
				</ul>
				<ul class="list1">
					<li class="user-dropdown">
						{% if user.is_authenticated %}
							<img src="{% static 'img/user.png' %}">
							<strong class="user" style="text-transform: uppercase;">Hola {{ user.username }}</strong>
							<ul class="dropdown-content">
								<li><a href="{% url 'usuarios:mi_cuenta' %}">MI CUENTA</a></li>
								<li><a href="{% url 'logout' %}"> CERRAR SESIÓN</a></li>
							</ul>
						{% else %}
							<a href="{% url 'login' %}"><i class="fas fa-sign-in-alt" style="margin-right: 5px;"></i> INICIAR SESIÓN</a>
							<a href="{% url 'usuarios:registro' %}"><i class="fas fa-user-plus" style="margin-right: 5px;"></i> REGISTRARSE</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</nav>
	</header>

	

	<div class="bloque">
	{% block contenido %}

	{% endblock contenido %}
	</div>


	<!-- Footer -->
	<footer class="footer">
		<div class="cluster1">
			<div class="box">
				<figure>
					<a href="#">
						<img src="{% static 'img/logo-sa.png' %}" alt="">
					</a>
				</figure>
			</div>
			<div class="box">
				<h2>SOBRE NOSOTROS</h2>
				<p>"S.A.: Tu fuente confiable de noticias sobre Inteligencia Artificial.</p>
				<p>
					"¡Únete a nosotros en este emocionante viaje! Inspírate, desafía tu 
					pensamiento y encuentra en nosotros tu destino confiable para todo sobre Inteligencia Artificial."</p>
			</div>
			<div class="box">
				<h2>SIGUENOS EN NUESTRAS REDES</h2>
				<div class="red-social">
					<a href="#" class="fa fa-facebook"></a>
					<a href="#" class="fa fa-instagram"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-youtube"></a>
					<a href="#" class="fa fa-linkedin"></a>
				</div>
			</div>
		</div>
		<div class="cluster2">
			<small>&copy; 2023 <b>Sandoval Alexis</b> - Todos los Derechos Reservados.
			<p>Quitilipi - Chaco, Argentina.</p></small>
		</div>
	</footer>
</body>
</html>

templates/t_contacto.html
<!-- Sección de Contacto -->
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Contacto - SA{% endblock titulo %}


{% block contenido %}
<section id="contacto">
    <div class="contacto-contenedor">
        <div class="contacto-info">
            <h2>Contacto</h2>

            <!-- Información de Contacto -->
            <div class="info-contactos">
                <p>¡Estamos aquí para ayudarte! Ponte en contacto con nosotros.</p>
                <ul>
                    <h1><i class="fa fa-envelope" aria-hidden="true"></i> Correo Electronico</h1>
                    <p>sandoval.alexis.emanuel@gmail.com</p>
                    <h1><i class="fa fa-phone" aria-hidden="true"></i> Teléfono</h1>
                    <p>+54 9 364 4674907</p>
                    <h1><i class="fa fa-map-marker" aria-hidden="true"></i> Dirección</h1>
                    <p>Buenos Aires 46, Quitilipi - Chaco, Argentina</p>
                </ul>
            </div>
            <!-- Redes Sociales -->
            <div class="social-media">
                <p>Síguenos en nuestras redes sociales para obtener las últimas actualizaciones:</p>
                <ul>
                    <li><a href="https://www.facebook.com/tudominio"><i class="fab fa-facebook"></i></a></li>
                    <li><a href="https://twitter.com/tudominio"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="https://www.linkedin.com/company/tudominio"><i class="fab fa-linkedin"></i></a></li>
                    <li><a href="https://www.instagram.com/company/tudominio"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="https://www.youtube.com/company/tudominio"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
        <div class="mapa">
            <!-- Mapa de Ubicación -->
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1258.2489643919805!2d-60.21945382700445!3d-26.876014007766504!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2sar!4v1702683593964!5m2!1ses-419!2sar" width="450" height="540" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</section>

{% endblock contenido %}

templates/t_home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Blog de Inteligencia Artificial - SA{% endblock titulo %}

{% block contenido %}

<!-- Lista de imagenes -->
<body>
	
	<div class="slider-box">
		<ul>
			<li>
				<img src="{% static 'img/IA-1.jpg' %}">
			</li>
			<li>
				<img src="{% static 'img/IA-2.jpg' %}">
			</li>
			<li>
				<img src="{% static 'img/IA-3.jpeg' %}">
			</li>
		</ul>
		<div class="texto">
			<p>La IA no te sustituirá, una persona que use IA lo hará</p>
		</div>
	</div>
	
	<div class="portada">
		<h2>¿Qué es la IA?</h2>
		<p>La Inteligencia Artificial es como la magia de la computación. Son programas y máquinas que pueden hacer cosas inteligentes, 
			como aprender, pensar, entender cosas y resolver problemas, ¡como lo haría una persona!</p>
		<p class="division"></p>
	</div>
	<div class="portada-2">
		<p>Hoy en día la IA está avanzando muchísimo y está cambiando la forma en que vivimos. Es como tener asistentes mágicos en nuestras 
			computadoras y teléfonos que hacen cosas increíbles para nosotros.</p>
		<p class="division"></p>
	</div>
	<div class="portada-3">
		<p>En este blog, vamos a explorar todo lo emocionante que la IA está haciendo en el mundo hoy en día. Únete a nosotros para descubrir 
			este mundo mágico de la Inteligencia Artificial!</p>
		<p class="division"></p>
	</div>

	<h2 class="titulo-noti-reciente">Noticias Recientes</h2>
	<ul class="contenedor-noticias-recientes">
		{% for noticia in ultimas_noticias %}
			<li>
				<img src="{{ noticia.imagen.url }}" alt="{{ noticia.titulo }}">
				<div class="contenido-noti">
					<h3>{{ noticia.titulo }}</h3>
					<p>Categoria: {{ noticia.categoria_noticia }}</p>
					<p>Fecha de Publicación: {{ noticia.fecha }}</p>
					<a href="{% url 'noticias:detalle' pk=noticia.pk %}">Leer más</a>
				</div>
			</li>
		{% endfor %}
	</ul>

</body>
{% endblock contenido %}

templates/t_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Acerca de Nosotros - SA{% endblock titulo %}


{% block contenido %}
<div class="nosotros">
	<h2>Bienvenidos a S.A.</h2>
	<div class="fondo-nosotros1">
		<div class="nosotros1">
			<img src="{% static 'img/logo2-sa.jpeg' %}" alt="">
		<p>
			Somos un equipo apasionado por la Inteligencia Artificial y estamos encantados de tenerte aquí. 
			En S.A., estamos comprometidos a ser tu fuente confiable de noticias e información 
			sobre los avances más recientes en el emocionante campo de la IA.
		</p>
		</div>
	</div>
	
	<div class="nosotros2">
		<img src="{% static 'img/nosotros.jpg' %}" alt="">
		<p>
			En este espacio, encontrarás noticias, análisis profundo, y perspectivas variadas sobre cómo la IA 
			está transformando el presente y el futuro. Además, destacamos la ética, la responsabilidad y la 
			diversidad en el uso de la IA para contribuir a un desarrollo tecnológico más equitativo y sostenible.
		</p>
	</div>
	<div class="fondo-nosotros2">
		<div class="nosotros3">
			<img src="{% static 'img/nosotros2.png' %}" alt="">
		<p>
			Gracias por unirte a nosotros en este viaje emocionante. ¡Esperamos inspirarte, desafiarte a pensar 
			de manera diferente y ser tu destino confiable para todo lo relacionado con la Inteligencia Artificial!
		</p>
		</div>
		<div class="equipo">
			<p>
				El Equipo de Error-404
			</p>
		</div>
	</div>
</div>
	
	
{% endblock contenido %}